// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgqgklcalmtdcbaqurhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncWdrbGNhbG10ZGNiYXF1cmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTE0NzYsImV4cCI6MjA3NDI2NzQ3Nn0.Gxl-ir8hbysvzXgVJsopREYgsDH1ADac-C9xbrBmCP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});